### ISSUE TITLE
"con" is not a connection error in download_jira_data.Rmd

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#146] opened 2023-02-07 11:51 UTC
Hello Carlos,

While running download_jira_data.Rmd, I come across an error on this line:

https://github.com/sailuh/kaiaulu/blob/f66bc0f964861b8c928cda01c6b4b493414bf13a/vignettes/download_jira_data.Rmd#L88

Error in writeLines(json, path, useBytes = TRUE) :
'con' is not a connection

 2 . writeLines(json, path, useBytes = TRUE)
 1 . jsonlite::write_json(json_issues, save_path_issue_tracker_issues)

I double checked my filepaths and package installations, but that didn't seem to be the issue. In addition, json_issues
https://github.com/sailuh/kaiaulu/blob/f66bc0f964861b8c928cda01c6b4b493414bf13a/vignettes/download_jira_data.Rmd#L72

was not empty after running the line, so I'm confused on what could be wrong.

Relevant section of project configuration file used with download_jira_data.Rmd:

```
issue_tracker:
  jira:
    # Obtained from the project's JIRA URL
    domain: https://issues.apache.org/jira
    project_key: THRIFT
    # Download using `download_jira_data.Rmd`
    issues:
    issue_comments:
  github:
    # Obtained from the project's GitHub URL
    owner: apache
    repo: thrift
    # Download using `download_github_comments.Rmd`
    replies:
```

Also for reference I have jsonlite version 1.8.4 installed.

Thank you,
Leilani

**Comment by carlosparadis** [comment] 2023-02-09 01:46
Hi Leilani,

Thank you for including the config file! Your issue lies on the `issues:` and `issue_comments:`. This is how it should look like:

https://github.com/sailuh/kaiaulu/blob/f66bc0f964861b8c928cda01c6b4b493414bf13a/conf/geronimo.yml#L59-L60

In other words, while it is true you are downloading the issues, you did not specify in the config file where they should be saved (and further referenced). For some functionality in Kaiaulu, we use the `/tmp` folder and don't ask the user. However, for key datasets that may be needed in future analysis, we want to store them locally. Issue and Issue comments are very vital for all the analysis, hence why this is asked.

In regards to doing that with Thrift, there is more to this than it may appear on the surface. For now, I suggest you use the config file you see in the example on itm0 docs, which is the geronimo config I specified above.

In the [Social Smells Notebook Introduction](http://itm0.shidler.hawaii.edu/kaiaulu/articles/social_smell_showcase.html#introduction-1) I noted the following:

> Examples of issue tracker types include [JIRA](https://www.atlassian.com/software/jira), GitHub’s built-in Issue [Trac](https://trac.edgewall.org/)ker, GitLab’s Issue Tracker, Monorail (used in Google’s Chromium), Trac, Bugzilla, etc. You may also be interested in including discussion that occurs in GitHub’s pull requests / GitLab merge requests. Of the above, GitHub Issue Tracker comments, GitHub Pull Requests comments (download_github_comments.Rmd), and JIRA comments (download_jira_data.Rmd) are currently supported. See the associated vignettes for details on how to download the data.

To define a config for Thrift, you will fist want to figure out what they are using. Not every project in Apache Software Foundation uses JIRA (some use Bugzilla!). 

You will normally find this information on the project website (which varies from project to project): https://thrift.apache.org/

In their case, the mention is under the `Developers` page: https://thrift.apache.org/developers 

Which seems to confirm they have JIRA indeed: http://issues.apache.org/jira/browse/THRIFT 

At this point you can confirm that their key is THRIFT: https://issues.apache.org/jira/projects/THRIFT/issues/ 

I am not sure if you followed these steps, or guessed the key to be THRIFT, but I see that listed on the config file which is correct! 

This is part of the reason the config files exist: Distilling this type of information in a way that is readable, shareable, and usable by Kaiaulu too for reproducibility.

So I am hopeful once you specify the paths as shown on geronimo config, it should work. If you need to look for examples for a particular Notebook that "should work", itm0 is a good start since all the notebooks there have to be executable to be displayed on documentation.

Let me know if you can't get Thrift to work and/or Geronimo!

----

On another note, since this was not clear, would you mind adding a sub-section to https://github.com/sailuh/kaiaulu/wiki#12-project-configuration-files briefly explaining what I mentioned above on how someone would go about browsing a project to find the information to add to the configuration file to run the JIRA Notebook?

**Comment by leilani-reich** [comment] 2023-02-09 10:24
Hi Carlos,

I misinterpreted what I needed to put for the issues & comments paths; thanks for clearing that up, and for explaining how to define a config file in more detail!

After specifying paths for issues & issue comments, I tested out running dowload_jira_data.rmd for my own thrift.yml and Kaiaulu's geronimo.yml and both worked correctly.

One thing I did note was that kable doesn't seem to correctly render the table for the thrift jira issues.

This line:
https://github.com/sailuh/kaiaulu/blob/f66bc0f964861b8c928cda01c6b4b493414bf13a/vignettes/download_jira_data.Rmd#L97

Gives the following rendered output in RStudio:

---

issue_key | issue_summary | issue_type | issue_status | issue_components | issue_description | issue_created_datetimetz | issue_updated_datetimetz | issue_resolution_datetimetz | issue_creator_id | issue_creator_name | issue_creator_timezone | issue_reporter_id | issue_reporter_name | issue_reporter_timezone | issue_resolution | issue_assignee_id | issue_assignee_name | issue_assignee_timezone
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
THRIFT-5675 | Support SASL transport in Rust | New Feature | Open | Rust - Library | In the latest version of thrift’s rust implementation, there is no SASL transport available yet. |   |   |   |   |   |   |   |   |   |   |   |   |  

<p style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This blocks any implementation that wants to connect to hadoop/ hive over thrift in Rust. |2022-12-20T06:40:25.000+0000 |2022-12-20T06:40:25.000+0000 |NULL |chitralverma |Chitral Verma |America/Los_Angeles |chitralverma |Chitral Verma |America/Los_Angeles |NA |NA |NA |NA | |THRIFT-5674 |Server implementation exceptions are not sent to client in ES6 promise-style invocation |Bug |Open |JavaScript - Compiler |When a server implementation throws a user-defined exception, the server crashes and the exception is not sent to the client.  I believe this issue only happens in the Promise-style invocation of code generated for ES6.  Specifically, I think it arises from this line:</p><p style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">[https://github.com/apache/thrift/blob/0.17.0/compiler/cpp/src/thrift/generate/t_js_generator.cc#L1484]</p><p style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Generated code looks like the following (generated from the Calculator.calculate example): {code:java} Promise.resolve(this._handler.calculate.bind(this._handler)(   args.logid, args.w )).then( … ).catch(err =&gt; {   if (err instanceof ttypes.InvalidOperation) { … } );{code} The implementation-generated exception is handled by the promise chain.  The problem is that the implementation (handler) method is called<span> </span><em>before</em><span> </span>Promise.resolve, so any exception it throws is not handled by the promise chain.  So, when running{<sup>}1{</sup>} NodeServerPromise.js and NodeClientPromise.js from the tutorial, the server crashes when InvalidOperation is thrown and the client does not receive InvalidOperation (or anything further).</p><p style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">I think the minimal fix would be to generate something like the following instead: {code:java} new Promise((resolve) =&gt; resolve(this._handler.calculate.bind(this._handler)( args.logid, args.w ))).then( … ).catch(err =&gt; { if (err instanceof ttypes.InvalidOperation) { … } );{code} When making this change on the generated tutorial code and re-running{<sup>}1{</sup>} the server and client, the server stays up and both the server and client log five lines, as expected.</p><p style="color: rgb(0, 0, 0); font-family: Times; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><em>[1] There also seems to be a couple of errors in NodeClientPromise.js in the tutorial code.  I had to change “fail” to “catch” and “fin” to “finally” to get it to work.</em><span> </span>|2022-12-18T18:57:57.000+0000 |2022-12-18T19:19:18.000+0000 |NULL |cjmay |Chandler May |America/New_York |cjmay |Chandler May |America/New_York |NA |NA |NA |NA |</p>

---


The actual jira tables are fine, and I got correctly rendered tables for other cells, but I just wanted to let you know about this weirdness. For reference, I'm using knitr version 1.41.


I will work on adding a subsection in the Wiki in regards to browsing a project and acquiring information for a config file. 

Thank you!
Leilani

**Comment by carlosparadis** [comment] 2023-02-09 10:35
Unfortunately, Kable does indeed lose formatting when rendering in HTML, but the data itself I believe is properly represented within R memory. This would be an issue you would need to bring to the Kable project itself (much as you did to Perceval). 

There are other table rendering libraries too, but I wouldn't worry too much about it unless the R representation is not represented correctly. 

Please let me know if, for some reason, you don't have Wiki edit permissions in Kaiaulu, and I will try to fix it!

Glad both projects now work :)

**Comment by leilani-reich** [comment] 2023-02-09 10:40
Hi Carlos,

It doesn't look like I have Wiki edit permissions in Kaiaulu. I can only view it.

So I do not need to go through the CONTRIBUTING.md steps for editing the Wiki?

Thanks

**Comment by carlosparadis** [comment] 2023-02-09 11:11
I changed your permissions, give it another try on the wiki. This may incidentally enable a few other things (e.g. ability to label issues), but you can ignore that. 

No need to follow CONTRIBUTING.md for the wiki. That is mainly for code contribution only. :)

**Comment by leilani-reich** [comment] 2023-02-10 06:49
Hi Carlos, I updated the wiki with the subsection on setting up the config file for a specific project. Let me know if it needs revision, thanks!

**Comment by carlosparadis** [comment] 2023-02-10 08:40
Yes, this looks good! I just added a sub-header. I will go ahead and close the issue then. Thanks!

**Closed by carlosparadis** 2023-02-10 08:40 UTC
Labels: documentation, download
