### ISSUE TITLE
DV8 filenames mismatch with Perceval

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#183] opened 2023-04-11 11:31 UTC
Refer to https://github.com/sailuh/kaiaulu/pull/171#issuecomment-1501706352

**Comment by carlosparadis** [comment] 2023-04-13 11:08
I am confused with this issue. Is this a duplicate of #172? Or #184?

**Comment by leilani-reich** [comment] 2023-04-13 12:41
Hi Carlos,
yes I think this #183 and #184 are referring to the same thing. I can delete this issue.

**Comment by carlosparadis** [comment] 2023-04-13 19:32
No worries, lets just mark it as duplicate on the label and close!

**Closed by carlosparadis** 2023-04-13 19:32 UTC
Labels: status:duplicate
