### ISSUE TITLE
Social smells computation from multiple branches

### ISSUE THREAD

**Issue by mumtaz-haris** [sailuh/kaiaulu#132] opened 2021-09-21 04:59 UTC
Does Kaiaulu provide support for automatically selecting the branches, calculating smells, and integrating the results (of all the branches)?

**Comment by carlosparadis** [comment] 2021-09-21 05:45
Sort of. You can automatically (or more specifically programmatically) select branches or commits using the git_checkout function (Git treats them as the same). In fact, this is done in the Social Smells Notebook itself already when calculating static metrics (Line Metrics):

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/vignettes/social_smell_showcase.Rmd#L468

You could call this function at the start of the notebook, before parse_gitlog() is invoked and specifying the branch of interest, so the parsed git logs (and subsequently the smells) are also calculated in the branch. These are the current flags passed to generate the git log from parse_gitlog(), i.e. you won't enter the if that is currently hardcoded to master:

https://github.com/sailuh/kaiaulu/blob/5a003899207fd55980a9d9df1c5584e339854508/R/parser.R#L27-L39

With that being said, I do not currently have on the Kaiaulu's Git module a git_branch() function which would return all available branches (so you could loop on them). However, my understanding is that you would want to look at only release branches that have ongoing maintenance after release, which would require you manually going through the said list to specify them. If that was the case, specifying them at the start of the notebook, and looping the notebook through could achieve what I think you have in mind.

I believe starting from the communication network would be the lower hanging fruit for now in light of that.

What do you think?

**Comment by harismumtaz18** [comment] 2021-09-22 04:19
Thanks for the details. For listing the branches, I think we can try this git command: `$ git branch -a`
This command produces the list of branches of a project. We can use the list to iterate through all the branches. Using the same list of branches, we can get the branch git hash to checkout each branch using this command: `$ git rev-parse branch-name`
What do you think?

**Comment by carlosparadis** [comment] 2021-09-22 05:50
Are we interested only in release branches or every branch available? Yes, git branch is fine, I meant that we need to code a wrapper to invoke it in `git.R`. That's why I suggested started with the mailing list which the code is already there to download.

Also, I am not sure I understand your choice of `git rev-parse-branch-name`. We still want to specify for a given branch, a time interval of interest, with the point where a feature is introduced, no? (As you did for master). If that is the case, you would need to specify the hash interval for all branches for each project instead of choosing any commit hash, no?

**Comment by carlosparadis** [comment] 2021-09-26 07:41
I have added a git_checkout() at the start of the new social smell notebook https://github.com/sailuh/kaiaulu/commit/e17a54141d4d367cb61684b3d58a1afe2884d4a1

https://github.com/sailuh/kaiaulu/blob/e17a54141d4d367cb61684b3d58a1afe2884d4a1/vignettes/social_smell_showcase.Rmd#L98

Which now expects the branch to be specified via the project configuration file:

https://github.com/sailuh/kaiaulu/blob/e17a54141d4d367cb61684b3d58a1afe2884d4a1/vignettes/social_smell_showcase.Rmd#L73

Note the branch information is also used later in the code: https://github.com/sailuh/kaiaulu/blob/e17a54141d4d367cb61684b3d58a1afe2884d4a1/vignettes/social_smell_showcase.Rmd#L517. 

Hence this avoid confusion when restarting the branch state on full execution. 

There is currently no way to list all the branches nor loop through them using all the social smells. I will close this issue, but feel free to re-open if something is not clear.

**Comment by carlosparadis** [comment] 2021-09-27 06:55
I'm re-opening this after today's discussion:

1) We want a more sane way to loop through various branches. The new project configuration file now accommodates that:

https://github.com/sailuh/kaiaulu/blob/0677affcb3e4ca67f4f956880b96bd28391ed3f4/conf/helix.yml#L35-L42

So the social smell notebooks have to be edited to loop through them. A giant loop does not properly in the notebook given the nature of code blocks (not to mention the readability would plumb), so I will try and see if I can flash it out on the CLI instead which is what it was designed for. 

2) There has to be a mechanism that removes overlapping commits from all branches before smells are computed, or we will count them twice. There is also an issue with the smells being computed on 3 months time window. Finally, there is a question on what the branch is a branch from in the first place, as it may not always be from master. Figuring out a way to resolve all this automatically may require more involved tooling with the `git` interface. Alternatively, we could try to compare the smells from different branches side by side if all else fails. I will give some thought.

**Comment by rnkazman** [comment] 2021-09-27 16:36
I am not sure what you mean by "overlapping commits".  Can you
explain/provide an example?

Thanks.

**Comment by rnkazman** [comment] 2021-09-28 02:02
Got it.  My gut feeling is that this is a corner case, but we should
probably check that.  Most projects branch off of and fork back onto
master.  To do otherwise is the road to madness.  The question is: how
could we automatically determine if this convention is ever violated.

**Comment by rnkazman** [comment] 2021-09-28 02:11
I am not sure what you mean by "If the branch only has a few commits, note we will end up ignoring it regardless since social smells are currently being computed on 3-month time windows."  If the commits happen within the 3-month window then they will be counted, since we are (planning on) merging everything from all branches together.

And, yes, we are not using any line metrics at this point, so I don't think this is an issue.

**Comment by rnkazman** [comment] 2021-09-28 02:12
Finally, with respect to this comment: "We should consider if analyzing the social smells of all branches separately, per project, wouldn't also answer the research question. If so, then we need not add any more overhead here. We would just compute them independently and observe if their behavior separately follows the same trend consistently inter and intra project." the concern is that (many) individual branches won't have enough "mass"--enough commits and communications--for meaningful analysis.  That is, again, why we want to glom everything together.

**Comment by carlosparadis** [comment] 2021-09-28 03:10
If we want them to "have enough mass", then what we have should be the way to go: 

We run the social smells per branch. When I say per branch, I mean we calculate the social smells in the example above for:

`master=c1,c2,c3,c4,c5`.
`feature-1 = c1,c2,c3,c6,c7,c8` and

We plot the social smells for each branch over time, so we would have 2 lines now instead of 1 per project. We would expect that if a time window covers `c1,c2,c3` in common, then both lines will merely overlap on the plot. At the point there is divergence in commits due to the branch, said plot will just show the lines of social smells over time diverging. 

My understanding is that for our RQ, what we care about now is then if **both the lines diverge downwards or upwards** (i.e. consistently). 

If this setup is fine, then we already have the code for this. Let's call this Setup A.

-----

In the alternative setup which was my understanding of the meeting, let's call it B, the goal was trying to end up with "one line of smells over time per project", which then would require to "set union the smells", and introduce the commit overlap. This complicates the pre-processing for the sake of "ending up with 1 timeline of social smells per project that account for all branches".

------

Hence why I am wondering if we can't answer the same RQ by looking for consistency on the behavior for all branch lines (Setup A), vs trying to sum up somehow all branch lines into 1 (Setup B). Can we conclude what we want from Setup A? If so, we're good to go.

**Comment by rnkazman** [comment] 2021-09-28 16:51
My worry about your first proposal is that many (most?) branches won't last long enough/have enough data to make for meaningful analyses on their own.  Do you have any feel for this?

**Comment by carlosparadis** [comment] 2021-10-01 10:30
I have added a CLI interface for the multi-branch run so @mumtaz-haris only needs to specify the branches on the project configuration file, and this will do the rest. E.g. for Helix:

<img width="973" alt="Screen Shot 2021-10-01 at 2 48 27 AM" src="https://user-images.githubusercontent.com/17270563/135605399-71da2998-f1ff-4e31-ac76-a87b8a7df120.png">



The output table will resemble the same as before plus an added column specifying the branch:

<img width="979" alt="Screen Shot 2021-10-01 at 2 43 39 AM" src="https://user-images.githubusercontent.com/17270563/135604943-74f97424-64ec-4093-b365-e5407b05bde8.png">

This should make it easy to compare if projects which branches had many commits ahead also had the same smell counts as a sanity check.

Note this CLI endpoint only compute the smells which is the object of interest instead of a number of other metrics (churn, Line metrics, etc), and also to stay consistent with the CLI interface in Kaiaulu for single responsibility. 

----

I will follow up with @rnkazman on the method (whether this one or something else to combine all smells) over some time this week. Meanwhile, @mumtaz-haris will try to test the code on a different project, preferably one we would expect different smells, for the project config files he already has ready to sanity test. 

----

There is a chance the code may need to be edited so it specifies the time range in dates rather than commit hashes for the interval of interest we want (like the commit hash interval I'd expect to be unique for each branch).

**Comment by carlosparadis** [comment] 2021-10-02 09:18
I have made a few corrections to the concern on my previous comment to specify date times instead of commit hashes. The screenshot of the output has been accordingly updated, and the divergence on branches can now be observed on it. 

Furthermore, I got the chance to talk with @rnkazman today to clarify the approach, and we are good to go to move forward with the CLI for multibranch analysis.

@mumtaz-haris The ball is on your court unless another problem shows up when you try to run this for the other projects.

**Closed** 2021-10-16 20:00 UTC
Labels: smells, parser
